### ISSUE TITLE
Problem with lost empty line 

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp-yaml#29]
For example:

Original part of yaml:
```
unit-tests:
  cases:
    - name: "NormalizeUnitTestName"
      description: "Test Normalize UnitTest Name"
    - name: "generateFilenameForUnitTest"
      description: "Test generate filename for UnitTest"
    - name: "InitPackage"
      description: "Test for init package"
      enabled: "no"
    - name: "ReadPackage"
      description: "Test for read package"

resources:
  - filepath: "./build_simple.sh"
    filesize: 77
    pack-as: "binary"
    modified: 1600401759
    sha1: ""

```

After save - empty lines will be lost:

```
unit-tests:
  cases:
    - name: "NormalizeUnitTestName"
      description: "Test Normalize UnitTest Name"
    - name: "generateFilenameForUnitTest"
      description: "Test generate filename for UnitTest"
    - name: "InitPackage"
      description: "Test for init package"
      enabled: "no"
    - name: "ReadPackage"
      description: "Test for read package"
resources:
  - filepath: "./build_simple.sh"
    filesize: 77
    pack-as: "binary"
    modified: 1600401759
    sha1: ""
```
