### ISSUE TITLE
add new methods for add elements to Cursor

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp-yaml#30]
`::afterItSet(name, value) # fixing pushing after empty lines `

```
some: 
  - n1: 1
    n2: 2

some2: r 
```

If use usually method for push:
```
some: 
  - n1: 1
    n2: 2

    n3: 3
some2: r 
```
